### ISSUE TITLE
sparsebak receive vm-name --save-to /dev/qubes_dom0/vm-name" isn't in thin provisioning 

### ISSUE THREAD

**Issue by tlaurion** [tasket/sparsebak#37]
But takes the whole flat space of Qubes volume.

Is that normal?

**Comment by tasket** [comment]
I don't understand the description of the problem.

Are you saying it creates a non-thin (not in the pool) volume? Or saves the volume in a non-sparse way?

In the output for `lvs`, is the saved volume shown with a pool name in the "pool" column?

**Comment by tlaurion** [comment]
It fills all my available pool size and have to break the restoration and lvremove the volume before restoration completes, unfortunately.

So I would guess the proper wording would be that the volume saved is non-thin.




On July 12, 2019 12:51:27 PM UTC, tasket <notifications@github.com> wrote:
>I don't understand the description of the problem.
>
>Are you saying it creates a non-thin (not in the pool) volume? Or saves
>the volume in a non-sparse way?
>
>In the output for `lvs`, is the saved volume shown with a pool name in
>the "pool" column?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tasket/sparsebak/issues/37#issuecomment-510874662

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tasket** [comment]
@tlaurion Please do an `lvdisplay vg/volumename` and post the "LV Pool name" and "Mapped size".

**Comment by tasket** [comment]
@tlaurion I wasn't able to reproduce the problem myself.

It sounds like the volume gets progressively larger as the `receive` operation is working (which is why you have to stop it?). If the volume were non-thin, the space would be taken all at once at the beginning. So this sounds like a thin volume that sparsebak is filling up (perhaps non-sparse-ly if it thinks there are no 'holes').

I posted a [modified version](https://github.com/tasket/sparsebak/tree/test) of sparsebak that you can use to see the volume size vs the amount of actual data. It does this before the retrieval process begins, and again at the end. Instead of `receive` you can do a simple `verify` to avoid filling up your drive; it will scan the volume and report the amount of data bytes used. The data bytes number should give you an idea why your drive was filling up.

**Comment by tlaurion** [comment]
deleted all vm-name-snap volumes to have enough space:
`sudo lvs|grep snap|awk -F " " {'print $1'}|while read line; do sudo lvremove /dev/qubes_dom0/$line -f; done`

Output:
```
LV Size                58.77 GiB
LV Name                vm-name
Mapped size            43.03%
```
@tasket : So I guess it was just bigger then I thought....

**Comment by tlaurion** [comment]
Note: sudo fstrim -av should be applied on shutdown for all VM, defined in all templates.

**Comment by tasket** [comment]
@tlaurion OK, good news!  Be careful with `fstrim` though... the default 'discard' mounting appears to behave differently (trims less) for a reason. Using `fstrim` consumes more metadata space, unless you defrag the filesystem first.

**Comment by tlaurion** [comment]
@tasket can you pinpoint to relevant discussions? I participated in the debate a while ago, and the actual deployed behavior doesn't fit LUKS on SSD.

Might have to detect disk type on install for QubesOS to have proper defaults from VM, lvm and LUKS container on SSD drives.

Thanks

On July 13, 2019 4:08:16 PM UTC, tasket <notifications@github.com> wrote:
>@tlaurion OK, good news!  Be careful with `fstrim` though... the
>default 'discard' mounting appears to behave differently (trims less)
>for a reason. Using `fstrim` consumes more metadata space, unless you
>defrag the filesystem first.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tasket/sparsebak/issues/37#issuecomment-511133713

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
